spring:
  datasource:
    url: jdbc:mysql://localhost:3306/RESTFUL_API_SERVER_BOOK?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: test1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
#      ?? ?? 2?? ??
      minimum-idle: 2
#      ?? 5? ?? ??
      maximum-pool-size: 5

  #  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 10MB
#      max-request-size: 10MB



  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate:
    #        dialect: "org.hibernate.dialect.MySQL5Dialect"
    show-sql: true

  thymeleaf:
    cache: false

#file:
#  dir: /Users/daewon/Study/file/
